# Generated by Django 4.1.1 on 2022-10-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmicpc', '0002_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
    ]
