# Generated by Django 4.1.1 on 2022-10-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmicpc', '0003_alter_submit_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='problem_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
